# Generated by Django 3.2.12 on 2022-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDatacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacenterid', models.IntegerField()),
                ('datacentername', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('startTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacenterid', models.IntegerField()),
                ('floorid', models.IntegerField()),
                ('floorname', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackid', models.IntegerField()),
                ('hostid', models.IntegerField()),
                ('hostname', models.CharField(max_length=30)),
                ('hostdescription', models.CharField(max_length=50)),
                ('hostType', models.CharField(max_length=20)),
                ('processors', models.IntegerField()),
                ('ipaddress', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hostactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('activityid', models.IntegerField()),
                ('power', models.FloatField()),
                ('power_mode', models.CharField(max_length=25)),
                ('stat1', models.FloatField()),
                ('stat2', models.FloatField()),
                ('stat3', models.FloatField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorid', models.IntegerField()),
                ('rackid', models.IntegerField()),
                ('rackname', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('pdu', models.IntegerField(null=True)),
            ],
        ),
    ]
