# Generated by Django 3.2.12 on 2022-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datacenter',
        ),
        migrations.AlterField(
            model_name='availabledatacenters',
            name='datacenterid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='availabledatacenters',
            name='datacentername',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='availabledatacenters',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='availabledatacenters',
            name='masterip',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
