# Generated by Django 3.2.12 on 2022-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('sub_id', models.CharField(max_length=15, null=True)),
                ('hostid', models.IntegerField(null=True)),
                ('power', models.FloatField(null=True)),
                ('time', models.IntegerField(null=True)),
            ],
        ),
    ]
