# Generated by Django 3.2.12 on 2022-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostenergy',
            name='hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='kWh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='minutes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='sub_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='total_watts',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='watt_hour',
            field=models.FloatField(null=True),
        ),
    ]
