# Generated by Django 3.2.12 on 2022-03-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostenergy',
            name='kWh_consumed',
            field=models.FloatField(null=True),
        ),
    ]
