# Generated by Django 3.2.12 on 2022-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostenergy',
            old_name='carbon_footprint',
            new_name='carbon_footprint_3',
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='ops_cons_3',
            field=models.FloatField(null=True),
        ),
    ]
