# Generated by Django 3.2.12 on 2022-02-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_hostenergy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostEnergy',
        ),
    ]
