# Generated by Django 3.2.12 on 2022-03-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20220303_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostenergy',
            name='op_cost_3',
            field=models.FloatField(null=True),
        ),
    ]
