# Generated by Django 3.2.12 on 2022-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20220331_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('current', models.CharField(max_length=25, null=True)),
                ('configured', models.IntegerField(null=True)),
                ('threshold_low', models.FloatField(default=15, max_length=25, null=True)),
                ('threshold_medium', models.FloatField(default=30, max_length=25, null=True)),
            ],
        ),
    ]
