# Generated by Django 3.2.12 on 2022-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_host_kwh_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='TCO',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='avg_kWh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='avg_watt_hour',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='capital',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='carbon_footprint_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='minutes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='op_cost_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ops_cons_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='total_watt_hour',
            field=models.FloatField(null=True),
        ),
    ]
