# Generated by Django 3.2.12 on 2022-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_delete_hostenergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('datacenterid', models.CharField(max_length=20, null=True)),
                ('floorid', models.IntegerField(null=True)),
                ('rackid', models.IntegerField()),
                ('hostid', models.IntegerField()),
                ('ipaddress', models.CharField(max_length=25)),
                ('TCO', models.FloatField(null=True)),
                ('carbon_footprint', models.FloatField(null=True)),
                ('ops_cons', models.FloatField(null=True)),
            ],
        ),
    ]
