# Generated by Django 3.2.12 on 2022-04-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_application_configured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.DeleteModel(
            name='CurrentDatacenter',
        ),
        migrations.DeleteModel(
            name='MasterIP',
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
