# Generated by Django 3.2.12 on 2022-03-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20220319_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='TCO',
        ),
        migrations.RemoveField(
            model_name='host',
            name='avg_kWh',
        ),
        migrations.RemoveField(
            model_name='host',
            name='avg_watt_hour',
        ),
        migrations.RemoveField(
            model_name='host',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='host',
            name='carbon_footprint_3',
        ),
        migrations.RemoveField(
            model_name='host',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='host',
            name='kWh_consumed',
        ),
        migrations.RemoveField(
            model_name='host',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='op_cost_3',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ops_cons_3',
        ),
        migrations.RemoveField(
            model_name='host',
            name='total_watt_hour',
        ),
    ]
