# Generated by Django 3.2.12 on 2022-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_hostenergy_app_waste_cost_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostenergy',
            name='lastTime',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
