# Generated by Django 3.2.12 on 2022-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_hostenergy_lasttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostenergy',
            name='cpu_lastTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='cpu_responses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='cpu_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hostenergy',
            name='total_cpu',
            field=models.FloatField(null=True),
        ),
    ]
